# Generated by Django 6.0.4 on 2026-04-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerprofile',
            old_name='pass_onboading',
            new_name='pass_onboarding',
        ),
    ]
