# Generated by Django 5.2.13 on 2026-04-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_pass_onboading_ownerprofile_pass_onboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='logo',
            field=models.ImageField(blank=True, default='logos/profile/default.png', upload_to='logos/profile'),
        ),
    ]
