# Generated by Django 6.0.3 on 2026-03-07 19:06

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', help_text='Nom du schéma.', max_length=120)),
                ('schema', models.JSONField(help_text='Structure du formulaire (JSON).')),
                ('public_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant public utilisé dans le widget.', unique=True)),
                ('is_default', models.BooleanField(default=True, help_text='Définit si ce schéma est celui par défaut.')),
                ('version', models.PositiveIntegerField(default=0, help_text='Version du schéma, augmente à chaque modification.')),
                ('double_opt_enable', models.BooleanField(default=True, help_text='Activer le double opt-in pour email/SMS.')),
                ('preferred_channel', models.CharField(choices=[('email', 'email'), ('phone', 'phone')], default='email', help_text='Canal préféré pour envoyer le code de vérification.', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(help_text='Le propriétaire de ce schéma', on_delete=django.db.models.deletion.CASCADE, related_name='form_schema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Schema',
                'verbose_name_plural': 'Form Schemas',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OwnerClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, help_text='Adresse MAC du device.', max_length=17)),
                ('payload', models.JSONField(help_text="Données brutes envoyées par l'utilisateur.")),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('client_token', models.CharField(blank=True, help_text='Token interne pour reconnaître le client.', max_length=64, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('recognition_level', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Data',
                'verbose_name_plural': 'Client Data',
                'indexes': [models.Index(fields=['owner', 'email'], name='core_data_o_owner_i_4cda27_idx'), models.Index(fields=['owner', 'phone'], name='core_data_o_owner_i_d8b05c_idx'), models.Index(fields=['owner', '-created_at'], name='core_data_o_owner_i_ee8486_idx'), models.Index(fields=['owner', '-last_seen'], name='core_data_o_owner_i_5b3be7_idx')],
                'unique_together': {('owner', 'client_token'), ('owner', 'mac_address')},
            },
        ),
    ]
