# Generated by Django 6.0.4 on 2026-04-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formschema',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='formschema',
            name='preferred_channel',
        ),
        migrations.AddField(
            model_name='formschema',
            name='enable',
            field=models.BooleanField(default=True, help_text='Active ou désactive le formulaire sur le portail captif.'),
        ),
        migrations.AlterField(
            model_name='formschema',
            name='double_opt_enable',
            field=models.BooleanField(default=False, help_text='Activer le double opt-in pour SMS.'),
        ),
        migrations.AlterField(
            model_name='formschema',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Version du schéma, augmente uniquement lors de changements structurels.'),
        ),
    ]
