# Generated by Django 6.0.4 on 2026-04-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0002_remove_formschema_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerclient',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes internes du propriétaire sur ce client.', null=True),
        ),
        migrations.AddField(
            model_name='ownerclient',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Tags pour qualifier le lead (ex: ['VIP', 'Nouveau'])."),
        ),
    ]
