# Generated by Django 5.2.13 on 2026-04-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0003_ownerclient_notes_ownerclient_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='formschema',
            name='button_label',
            field=models.CharField(blank=True, default='Accéder au WiFi', help_text='Texte du bouton de soumission du formulaire.', max_length=80),
        ),
        migrations.AddField(
            model_name='formschema',
            name='description',
            field=models.TextField(blank=True, default='Remplissez ce formulaire pour vous connecter.', help_text='Description/sous-titre affiché dans le formulaire widget.'),
        ),
        migrations.AddField(
            model_name='formschema',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL du logo affiché dans le formulaire widget.', null=True),
        ),
        migrations.AddField(
            model_name='formschema',
            name='title',
            field=models.CharField(blank=True, default='Bienvenue !', help_text='Titre affiché en haut du formulaire widget.', max_length=120),
        ),
    ]
