# Generated by Django 5.2.13 on 2026-04-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0004_add_appearance_fields_to_formschema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formschema',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='formschema',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo affiché dans le formulaire widget.', null=True, upload_to='logos/form'),
        ),
    ]
