# Generated by Django 6.0.4 on 2026-04-21 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0005_remove_formschema_logo_url_formschema_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formschema',
            name='double_opt_enable',
        ),
        migrations.AddField(
            model_name='formschema',
            name='conflict_strategy',
            field=models.CharField(choices=[('ALLOW', 'Laisser passer (Log uniquement)'), ('REQUIRE_OTP', 'Exiger une vérification OTP')], default='ALLOW', help_text="Action à entreprendre lorsqu'un email ou téléphone est déjà utilisé par un autre appareil.", max_length=20),
        ),
        migrations.AddField(
            model_name='formschema',
            name='opt',
            field=models.BooleanField(default=False, help_text='Activer la vérification OTP par SMS.'),
        ),
        migrations.CreateModel(
            name='ConflictAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_field', models.CharField(choices=[('email', 'Email'), ('phone', 'Téléphone')], max_length=10)),
                ('offending_payload', models.JSONField()),
                ('offending_mac', models.CharField(max_length=17)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('existing_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='core_data.ownerclient')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
