# Generated by Django 6.0.4 on 2026-04-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0006_remove_formschema_double_opt_enable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conflictalert',
            name='is_resolved',
        ),
        migrations.AddField(
            model_name='conflictalert',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('RESOLVED', 'Résolu'), ('IGNORED', 'Ignoré')], default='PENDING', max_length=10),
        ),
    ]
