# Generated by Django 6.0.4 on 2026-04-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0007_remove_conflictalert_is_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerclient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ownerclient',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
