# Generated by Django 6.0.4 on 2026-04-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0008_ownerclient_updated_at_alter_ownerclient_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerclient',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
