# Generated by Django 6.0.4 on 2026-05-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0011_clientdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formschema',
            name='conflict_strategy',
            field=models.CharField(choices=[('ALLOW', 'Rattachement silencieux (log uniquement)'), ('REQUIRE_OTP', "Demander une confirmation d'identité (Oui/Non)")], default='ALLOW', help_text="Comportement lors d'un conflit de contact : silencieux ou confirmation d'identité.", max_length=20),
        ),
    ]
