# Generated by Django 6.0.4 on 2026-04-29 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_data', '0009_ownerclient_user_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_fcfa', models.PositiveIntegerField(help_text='Prix du ticket en FCFA')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Durée du ticket en minutes (ex: 60 pour 1h, 240 pour 4h)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner', 'price_fcfa'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ticket_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('mikrotik_session_id', models.CharField(blank=True, db_index=True, help_text='$session-id MikroTik — clé de rapprochement avec on-logout', max_length=128, null=True)),
                ('session_key', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('session_timeout_seconds', models.PositiveIntegerField(default=0, help_text='Durée totale accordée au ticket en secondes ($uptime-limit)')),
                ('uptime_seconds', models.PositiveIntegerField(default=0)),
                ('bytes_downloaded', models.BigIntegerField(default=0)),
                ('bytes_uploaded', models.BigIntegerField(default=0)),
                ('amount_fcfa', models.PositiveIntegerField(default=0, help_text='Prix du ticket au moment de la connexion (copie de TicketPlan.price_fcfa)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('disconnect_cause', models.CharField(blank=True, default='', help_text='Raison de déconnexion transmise par MikroTik (session-timeout, lost-service, etc.)', max_length=64)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core_data.ownerclient')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to=settings.AUTH_USER_MODEL)),
                ('ticket_plan', models.ForeignKey(blank=True, help_text='Plan identifié automatiquement via uptime-limit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='tracking.ticketplan')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticketplan',
            index=models.Index(fields=['owner', 'is_active'], name='tracking_ti_owner_i_e3a3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='connectionsession',
            index=models.Index(fields=['owner', '-started_at'], name='tracking_co_owner_i_b5e997_idx'),
        ),
        migrations.AddIndex(
            model_name='connectionsession',
            index=models.Index(fields=['owner', 'mac_address'], name='tracking_co_owner_i_ac26db_idx'),
        ),
        migrations.AddIndex(
            model_name='connectionsession',
            index=models.Index(fields=['owner', 'is_active'], name='tracking_co_owner_i_bf10f5_idx'),
        ),
    ]
