# Generated by Django 5.2.13 on 2026-04-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='connectionsession',
            new_name='tracking_co_owner_i_b5e997_idx',
            old_name='tracking_co_owner_i_started_idx',
        ),
        migrations.RenameIndex(
            model_name='connectionsession',
            new_name='tracking_co_owner_i_ac26db_idx',
            old_name='tracking_co_owner_i_mac_idx',
        ),
        migrations.RenameIndex(
            model_name='connectionsession',
            new_name='tracking_co_owner_i_bf10f5_idx',
            old_name='tracking_co_owner_i_active_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketplan',
            new_name='tracking_ti_owner_i_e3a3b5_idx',
            old_name='tracking_ti_owner_i_active_idx',
        ),
        migrations.AddField(
            model_name='connectionsession',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
