# Generated by Django 6.0.4 on 2026-04-25 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_rename_tracking_co_owner_i_started_idx_tracking_co_owner_i_b5e997_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionsession',
            name='download_limit_bytes',
        ),
        migrations.RemoveField(
            model_name='connectionsession',
            name='upload_limit_bytes',
        ),
        migrations.RemoveField(
            model_name='ticketplan',
            name='download_limit_mb',
        ),
        migrations.RemoveField(
            model_name='ticketplan',
            name='upload_limit_mb',
        ),
        migrations.AddField(
            model_name='connectionsession',
            name='session_timeout_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Durée totale accordée au ticket en secondes'),
        ),
        migrations.AlterField(
            model_name='connectionsession',
            name='ticket_plan',
            field=models.ForeignKey(blank=True, help_text='Plan identifié automatiquement via session-timeout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='tracking.ticketplan'),
        ),
        migrations.AlterField(
            model_name='ticketplan',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Durée du ticket en minutes (ex: 60 pour 1h, 240 pour 4h)'),
        ),
    ]
