# Generated by Django 6.0.4 on 2026-04-25 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_remove_connectionsession_download_limit_bytes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MikroTikRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom lisible (ex: Boutique principale)', max_length=100)),
                ('host', models.CharField(help_text='IP ou domaine du routeur (ex: 192.168.88.1)', max_length=255)),
                ('port', models.PositiveIntegerField(default=8728, help_text='Port API MikroTik (8728 par défaut, 8729 en SSL)')),
                ('username', models.CharField(help_text='Identifiant API MikroTik', max_length=100)),
                ('_password_encrypted', models.BinaryField(db_column='password_encrypted', help_text='Mot de passe chiffré (Fernet)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Dernière synchronisation réussie', null=True)),
                ('last_error', models.TextField(blank=True, default='', help_text='Dernière erreur de connexion (vide si tout va bien)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mikrotik_routers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner', 'name'],
            },
        ),
        migrations.AddField(
            model_name='connectionsession',
            name='router',
            field=models.ForeignKey(blank=True, help_text='Routeur MikroTik source de la session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='tracking.mikrotikrouter'),
        ),
        migrations.AddIndex(
            model_name='mikrotikrouter',
            index=models.Index(fields=['owner', 'is_active'], name='tracking_mi_owner_i_ad621b_idx'),
        ),
    ]
